export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as TopNav } from './TopNav'
export { default as BotNav } from './BotNav'
export { default as Game} from './Game'